### ISSUE TITLE
KV Lang Area not saving to main.kv

### ISSUE THREAD

**Issue by MysticMight** [kivy/kivy-designer#271]
When I load my project the kivy file "main.kv" isn't recognised and so doesn't load in the KV Lang Area. When I double click it in the Project Tree it opens in the KV Lang Area with some mixed up text (probably due to me moving around widgets in a previous session).

e.g. main.kv file
```
<RootWidget>:
    # this is the rule for your root widget, defining it's look and feel.

    BoxLayout:
        orientation: 'vertical'

        Label:
            text: 'Label'
        GridLayout:
            Label:
            	text: ''
            Button:
            
            Label:
            
            Button:
            
            Label:
            
            Button:
            Label:
            Button:
            Label:
    text: 'Label'
    text: 'Button'
    text: 'Label'
    text: 'Label'
    text: 'Button'
    text: 'Label'
    text: 'Label'
    text: 'Button'
    text: 'Button'
    		cols: 3
    		rows: 3
```

The problem is when I try fix this and save, the file isn't updated. i.e. when I double click on the project tree file (which overwrites the KV Lang Area) or view the file externally. The Error Console also still shows a error (which was from before changing the code):
```
Error: 1
Parser: File "main.kv", line 24:
...
     22:            Button:
     23:            Label:
>>   24:    text: 'Label'
     25:    text: 'Button'
     26:    text: 'Label'
...
Invalid data after declaration
```
e.g. fixed form of the main.kv file: (unsaved)
```
<RootWidget>:
    # this is the rule for your root widget, defining it's look and feel.

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Label'
        GridLayout:
        	rows: 3
        	cols: 3
            Label:
            	text: '1'
            Button:
            	text: '2'
            Label:
            	text: '3'
```
Besides this issue, "Reload widgets" was updating the view, but I cannot manage to get it to occur again.
